from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .cover import NODE_CLASS_MAPPINGS as _COVER_NODES, NODE_DISPLAY_NAME_MAPPINGS as _COVER_NAMES

NODE_CLASS_MAPPINGS.update(_COVER_NODES)
NODE_DISPLAY_NAME_MAPPINGS.update(_COVER_NAMES)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
