from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .cover import NODE_CLASS_MAPPINGS as _COVER_NODES, NODE_DISPLAY_NAME_MAPPINGS as _COVER_NAMES
from .score import NODE_CLASS_MAPPINGS as _SCORE_NODES, NODE_DISPLAY_NAME_MAPPINGS as _SCORE_NAMES

for _nodes, _names in ((_COVER_NODES, _COVER_NAMES), (_SCORE_NODES, _SCORE_NAMES)):
    NODE_CLASS_MAPPINGS.update(_nodes)
    NODE_DISPLAY_NAME_MAPPINGS.update(_names)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
